# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_set.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(160, 40, 371, 371))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_3)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_4)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_7)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_5)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBox_3 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinBox_4 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.spinBox_4)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_8)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 470, 101, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "采样点数"))
        self.label_2.setText(_translate("MainWindow", "刀头四点位置："))
        self.label_3.setText(_translate("MainWindow", "一次刀头位置："))
        self.label_4.setText(_translate("MainWindow", "二次刀头位置："))
        self.label_5.setText(_translate("MainWindow", "三次刀头位置："))
        self.label_6.setText(_translate("MainWindow", "四次刀头位置："))
        self.label_10.setText(_translate("MainWindow", "刀头步进距离"))
        self.label_8.setText(_translate("MainWindow", "X轴坐标范围"))
        self.label_9.setText(_translate("MainWindow", "Y轴坐标范围"))
        self.label_7.setText(_translate("MainWindow", "锁相采样频率："))
        self.label_11.setText(_translate("MainWindow", "单点采样数"))
        self.label_12.setText(_translate("MainWindow", "锁相敏感"))
        self.label_13.setText(_translate("MainWindow", "刀头移动时延"))
        self.pushButton.setText(_translate("MainWindow", "设置完毕提交"))
        self.menu.setTitle(_translate("MainWindow", "设置"))

